# Generated by Django 3.2.1 on 2024-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genre_songgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='external_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='uri_spotify',
            field=models.CharField(max_length=1000),
        ),
    ]
